In [1]:
import pandas as pd
import folium

In [2]:
folium_map = folium.Map(location=[30.266926, -97.750519],
                        zoom_start=5,
                        tiles="CartoDB dark_matter")

folium.CircleMarker(location=[30.266926, -97.750519],fill=True).add_to(folium_map)
folium_map

In [3]:
#importing the data
#file = "airline_report.csv"
#file_df = pd.read_csv(file)
#file_df.head()

In [4]:
df =  pd.read_csv('Consumer_Airfare_Report__Table_1a_-_All_U.S._Airport_Pair_Markets.csv')
df.head()
df[(df['airport_1'] == 'AUS') & (df['Year'] >= 2007)]

,tbl,Year,quarter,citymarketid_1,citymarketid_2,city1,city2,airportid_1,airportid_2,airport_1,...,fare,carrier_lg,large_ms,fare_lg,carrier_low,lf_ms,fare_low,Geocoded_City1,Geocoded_City2,tbl1apk
156,Table 1a,2014,3,30423,30194,"Austin, TX","Dallas/Fort Worth, TX",10423,11259,AUS,...,175.60,WN,0.9900,175.39,WN,0.9900,175.39,"Austin, TX\r\n(30.264979, -97.746598)","Dallas/Fort Worth, TX\r\n(40.11086, -77.035636)",201431042311259AUSDAL
329,Table 1a,2008,2,30423,30466,"Austin, TX","Phoenix, AZ",10423,14107,AUS,...,160.68,WN,0.5900,159.93,US,0.3200,158.23,"Austin, TX\r\n(30.264979, -97.746598)","Phoenix, AZ\r\n(30.406931, -87.217578)",200821042314107AUSPHX
1380,Table 1a,2011,3,30423,31453,"Austin, TX","Houston, TX",10423,12266,AUS,...,165.58,CO,0.9300,165.88,UA,0.0600,161.26,"Austin, TX\r\n(30.264979, -97.746598)","Houston, TX\r\n(29.760803, -95.369506)",201131042312266AUSIAH
1556,Table 1a,2011,1,30423,30852,"Austin, TX","Washington, DC (Metropolitan Area)",10423,10821,AUS,...,245.90,WN,0.7500,247.45,DL,0.0800,217.25,"Austin, TX\r\n(30.264979, -97.746598)","Washington, DC (Metropolitan Area)\r\n(38.8920...",201111042310821AUSBWI
1675,Table 1a,2010,2,30423,30466,"Austin, TX","Phoenix, AZ",10423,14107,AUS,...,186.22,WN,0.6000,192.01,US,0.2800,175.27,"Austin, TX\r\n(30.264979, -97.746598)","Phoenix, AZ\r\n(30.406931, -87.217578)",201021042314107AUSPHX
2004,Table 1a,2010,1,30423,30852,"Austin, TX","Washington, DC (Metropolitan Area)",10423,10821,AUS,...,197.79,WN,0.6200,205.37,AA,0.1400,179.14,"Austin, TX\r\n(30.264979, -97.746598)","Washington, DC (Metropolitan Area)\r\n(38.8920...",201011042310821AUSBWI
2167,Table 1a,2008,2,30423,30977,"Austin, TX","Chicago, IL",10423,13232,AUS,...,188.34,WN,0.9700,189.09,WN,0.9700,189.09,"Austin, TX\r\n(30.264979, -97.746598)","Chicago, IL\r\n(41.775002, -87.696388)",200821042313232AUSMDW
2178,Table 1a,2010,3,30423,30194,"Austin, TX","Dallas/Fort Worth, TX",10423,11298,AUS,...,133.37,AA,0.9900,133.03,AA,0.9900,133.03,"Austin, TX\r\n(30.264979, -97.746598)","Dallas/Fort Worth, TX\r\n(40.11086, -77.035636)",201031042311298AUSDFW
2378,Table 1a,2012,1,30423,30194,"Austin, TX","Dallas/Fort Worth, TX",10423,11259,AUS,...,157.70,WN,0.9900,157.61,WN,0.9900,157.61,"Austin, TX\r\n(30.264979, -97.746598)","Dallas/Fort Worth, TX\r\n(40.11086, -77.035636)",201211042311259AUSDAL
2914,Table 1a,2012,2,30423,31703,"Austin, TX","New York City, NY (Metropolitan Area)",10423,12478,AUS,...,238.48,B6,0.7400,237.28,DL,0.1000,222.65,"Austin, TX\r\n(30.264979, -97.746598)","New York City, NY (Metropolitan Area)\r\n(40.1...",201221042312478AUSJFK
3143,Table 1a,2014,4,30423,32467,"Austin, TX","Miami, FL (Metropolitan Area)",10423,11697,AUS,...,194.09,WN,0.4600,189.32,WN,0.4600,189.32,"Austin, TX\r\n(30.264979, -97.746598)","Miami, FL (Metropolitan Area)\r\n(44.977479, -...",201441042311697AUSFLL
3190,Table 1a,2014,1,30423,31703,"Austin, TX","New York City, NY (Metropolitan Area)",10423,12391,AUS,...,201.92,WN,0.9500,199.02,WN,0.9500,199.02,"Austin, TX\r\n(30.264979, -97.746598)","New York City, NY (Metropolitan Area)\r\n(40.1...",201411042312391AUSISP
3365,Table 1a,2011,1,30423,33195,"Austin, TX","Tampa, FL (Metropolitan Area)",10423,15304,AUS,...,216.44,WN,0.6500,202.51,WN,0.6500,202.51,"Austin, TX\r\n(30.264979, -97.746598)","Tampa, FL (Metropolitan Area)\r\n(37.8606, -78...",201111042315304AUSTPA
3451,Table 1a,2008,4,30423,32467,"Austin, TX","Miami, FL (Metropolitan Area)",10423,11697,AUS,...,154.49,WN,0.4700,150.37,B6,0.2900,145.51,"Austin, TX\r\n(30.264979, -97.746598)","Miami, FL (Metropolitan Area)\r\n(44.977479, -...",200841042311697AUSFLL
3666,Table 1a,2008,1,30423,31703,"Austin, TX","New York City, NY (Metropolitan Area)",10423,12197,AUS,...,395.16,AA,0.7000,386.40,AA,0.7000,386.40,"Austin, TX\r\n(30.264979, -97.746598)","New York City, NY (Metropolitan Area)\r\n(40.1...",200811042312197AUSHPN
3846,Table 1a,2007,2,30423,30721,"Austin, TX","Boston, MA (Metropolitan Area)",10423,14307,AUS,...,241.60,WN,0.4900,219.25,WN,0.4900,219.25,"Austin, TX\r\n(30.264979, -97.746598)","Boston, MA (Metropolitan Area)\r\n(42.358894, ...",200721042314307AUSPVD
3895,Table 1a,2009,4,30423,31703,"Austin, TX","New York City, NY (Metropolitan Area)",10423,11618,AUS,...,253.78,CO,0.8600,255.02,AA,0.0400,243.87,"Austin, TX\r\n(30.264979, -97.746598)","New York City, NY (Metropolitan Area)\r\n(40.1...",200941042311618AUSEWR
4020,Table 1a,2013,4,30423,32575,"Austin, TX","Los Angeles, CA (Metropolitan Area)",10423,13891,AUS,...,284.19,WN,0.5800,281.74,WN,0.5800,281.74,"Austin, TX\r\n(30.264979, -97.746598)","Los Angeles, CA (Metropolitan Area)\r\n(34.052...",201341042313891AUSONT
4157,Table 1a,2013,3,30423,30852,"Austin, TX","Washington, DC (Metropolitan Area)",10423,11278,AUS,...,284.34,WN,0.5200,254.73,WN,0.5200,254.73,"Austin, TX\r\n(30.264979, -97.746598)","Washington, DC (Metropolitan Area)\r\n(38.8920...",201331042311278AUSDCA
4958,Table 1a,2009,3,30423,30852,"Austin, TX","Washington, DC (Metropolitan Area)",10423,10821,AUS,...,175.37,WN,0.6700,175.45,WN,0.6700,175.45,"Austin, TX\r\n(30.264979, -97.746598)","Washington, DC (Metropolitan Area)\r\n(38.8920...",200931042310821AUSBWI
4989,Table 1a,2010,2,30423,32575,"Austin, TX","Los Angeles, CA (Metropolitan Area)",10423,12954,AUS,...,160.83,B6,0.9300,159.52,F9,0.0100,153.69,"Austin, TX\r\n(30.264979, -97.746598)","Los Angeles, CA (Metropolitan Area)\r\n(34.052...",201021042312954AUSLGB
5065,Table 1a,2014,1,30423,31703,"Austin, TX","New York City, NY (Metropolitan Area)",10423,12953,AUS,...,247.69,AA,0.3400,248.97,WN,0.1300,197.22,"Austin, TX\r\n(30.264979, -97.746598)","New York City, NY (Metropolitan Area)\r\n(40.1...",201411042312953AUSLGA
5117,Table 1a,2013,1,30423,32457,"Austin, TX","San Francisco, CA (Metropolitan Area)",10423,14831,AUS,...,270.50,WN,0.7100,275.55,AA,0.1500,236.57,"Austin, TX\r\n(30.264979, -97.746598)","San Francisco, CA (Metropolitan Area)\r\n(37.7...",201311042314831AUSSJC
5184,Table 1a,2012,3,30423,30721,"Austin, TX","Boston, MA (Metropolitan Area)",10423,13296,AUS,...,242.36,WN,0.6200,230.80,WN,0.6200,230.80,"Austin, TX\r\n(30.264979, -97.746598)","Boston, MA (Metropolitan Area)\r\n(42.358894, ...",201231042313296AUSMHT
5293,Table 1a,2008,4,30423,32575,"Austin, TX","Los Angeles, CA (Metropolitan Area)",10423,10800,AUS,...,223.15,WN,0.5000,230.92,US,0.2300,206.99,"Austin, TX\r\n(30.264979, -97.746598)","Los Angeles, CA (Metropolitan Area)\r\n(34.052...",200841042310800AUSBUR
5349,Table 1a,2013,2,30423,33195,"Austin, TX","Tampa, FL (Metropolitan Area)",10423,15304,AUS,...,197.07,WN,0.6200,196.78,DL,0.1400,186.16,"Austin, TX\r\n(30.264979, -97.746598)","Tampa, FL (Metropolitan Area)\r\n(37.8606, -78...",201321042315304AUSTPA
5603,Table 1a,2012,2,30423,31703,"Austin, TX","New York City, NY (Metropolitan Area)",10423,15070,AUS,...,312.40,DL,0.8500,306.68,US,0.0600,289.25,"Austin, TX\r\n(30.264979, -97.746598)","New York City, NY (Metropolitan Area)\r\n(40.1...",201221042315070AUSSWF
5644,Table 1a,2011,4,30423,31703,"Austin, TX","New York City, NY (Metropolitan Area)",10423,12197,AUS,...,247.77,DL,0.4000,222.10,DL,0.4000,222.10,"Austin, TX\r\n(30.264979, -97.746598)","New York City, NY (Metropolitan Area)\r\n(40.1...",201141042312197AUSHPN
5915,Table 1a,2012,4,30423,31703,"Austin, TX","New York City, NY (Metropolitan Area)",10423,11618,AUS,...,289.36,UA,0.7800,299.09,AA,0.0700,218.44,"Austin, TX\r\n(30.264979, -97.746598)","New York City, NY (Metropolitan Area)\r\n(40.1...",201241042311618AUSEWR
5932,Table 1a,2009,2,30423,31703,"Austin, TX","New York City, NY (Metropolitan Area)",10423,12953,AUS,...,223.26,AA,0.5400,227.24,AA,0.5400,227.24,"Austin, TX\r\n(30.264979, -97.746598)","New York City, NY (Metropolitan Area)\r\n(40.1...",200921042312953AUSLGA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84291,Table 1a,2018,2,30423,30647,"Austin, TX","Cleveland, OH (Metropolitan Area)",10423,11042,AUS,...,178.22,G4,0.2946,86.15,F9,0.1305,74.50,"Austin, TX\r\n(30.264979, -97.746598)","Cleveland, OH (Metropolitan Area)\r\n(41.50554...",201821042311042AUSCLE
84292,Table 1a,2018,2,30423,31066,"Austin, TX","Columbus, OH",10423,11066,AUS,...,220.17,WN,0.3573,240.97,F9,0.2409,83.24,"Austin, TX\r\n(30.264979, -97.746598)","Columbus, OH\r\n(39.962649, -82.996216)",201821042311066AUSCMH
84293,Table 1a,2018,2,30423,30194,"Austin, TX","Dallas/Fort Worth, TX",10423,11259,AUS,...,184.21,WN,0.9998,184.20,WN,0.9998,184.20,"Austin, TX\r\n(30.264979, -97.746598)","Dallas/Fort Worth, TX\r\n(40.11086, -77.035636)",201821042311259AUSDAL
84294,Table 1a,2018,2,30423,30852,"Austin, TX","Washington, DC (Metropolitan Area)",10423,11278,AUS,...,304.74,WN,0.6865,291.38,WN,0.6865,291.38,"Austin, TX\r\n(30.264979, -97.746598)","Washington, DC (Metropolitan Area)\r\n(38.8920...",201821042311278AUSDCA
84295,Table 1a,2018,2,30423,31703,"Austin, TX","New York City, NY (Metropolitan Area)",10423,11618,AUS,...,250.28,UA,0.6317,271.58,WN,0.3162,199.17,"Austin, TX\r\n(30.264979, -97.746598)","New York City, NY (Metropolitan Area)\r\n(40.1...",201821042311618AUSEWR
84296,Table 1a,2018,2,30423,32467,"Austin, TX","Miami, FL (Metropolitan Area)",10423,11697,AUS,...,181.95,WN,0.5209,187.96,B6,0.3465,158.50,"Austin, TX\r\n(30.264979, -97.746598)","Miami, FL (Metropolitan Area)\r\n(44.977479, -...",201821042311697AUSFLL
84297,Table 1a,2018,2,30423,31453,"Austin, TX","Houston, TX",10423,12191,AUS,...,196.49,WN,1.0000,196.49,WN,1.0000,196.49,"Austin, TX\r\n(30.264979, -97.746598)","Houston, TX\r\n(29.760803, -95.369506)",201821042312191AUSHOU
84298,Table 1a,2018,2,30423,31703,"Austin, TX","New York City, NY (Metropolitan Area)",10423,12197,AUS,...,264.34,AA,0.4228,254.57,UA,0.1098,228.94,"Austin, TX\r\n(30.264979, -97.746598)","New York City, NY (Metropolitan Area)\r\n(40.1...",201821042312197AUSHPN
84299,Table 1a,2018,2,30423,30852,"Austin, TX","Washington, DC (Metropolitan Area)",10423,12264,AUS,...,294.15,UA,0.6923,334.64,F9,0.2036,140.98,"Austin, TX\r\n(30.264979, -97.746598)","Washington, DC (Metropolitan Area)\r\n(38.8920...",201821042312264AUSIAD
84300,Table 1a,2018,2,30423,31453,"Austin, TX","Houston, TX",10423,12266,AUS,...,220.65,UA,1.0000,220.65,UA,1.0000,220.65,"Austin, TX\r\n(30.264979, -97.746598)","Houston, TX\r\n(29.760803, -95.369506)",201821042312266AUSIAH
84301,Table 1a,2018,2,30423,31703,"Austin, TX","New York City, NY (Metropolitan Area)",10423,12391,AUS,...,237.65,WN,0.9111,239.54,WN,0.9111,239.54,"Austin, TX\r\n(30.264979, -97.746598)","New York City, NY (Metropolitan Area)\r\n(40.1...",201821042312391AUSISP
84302,Table 1a,2018,2,30423,31703,"Austin, TX","New York City, NY (Metropolitan Area)",10423,12478,AUS,...,240.10,DL,0.5206,253.41,B6,0.2874,219.43,"Austin, TX\r\n(30.264979, -97.746598)","New York City, NY (Metropolitan Area)\r\n(40.1...",201821042312478AUSJFK
84303,Table 1a,2018,2,30423,32575,"Austin, TX","Los Angeles, CA (Metropolitan Area)",10423,12892,AUS,...,194.45,AA,0.3727,200.71,WN,0.2813,178.40,"Austin, TX\r\n(30.264979, -97.746598)","Los Angeles, CA (Metropolitan Area)\r\n(34.052...",201821042312892AUSLAX
84304,Table 1a,2018,2,30423,31066,"Austin, TX","Columbus, OH",10423,12917,AUS,...,69.21,G4,1.0000,69.21,G4,1.0000,69.21,"Austin, TX\r\n(30.264979, -97.746598)","Columbus, OH\r\n(39.962649, -82.996216)",201821042312917AUSLCK
84305,Table 1a,2018,2,30423,31703,"Austin, TX","New York City, NY (Metropolitan Area)",10423,12953,AUS,...,232.80,WN,0.2574,223.70,F9,0.1092,122.50,"Austin, TX\r\n(30.264979, -97.746598)","New York City, NY (Metropolitan Area)\r\n(40.1...",201821042312953AUSLGA
84306,Table 1a,2018,2,30423,32575,"Austin, TX","Los Angeles, CA (Metropolitan Area)",10423,12954,AUS,...,164.23,B6,0.9538,163.05,B6,0.9538,163.05,"Austin, TX\r\n(30.264979, -97.746598)","Los Angeles, CA (Metropolitan Area)\r\n(34.052...",201821042312954AUSLGB
84307,Table 1a,2018,2,30423,30977,"Austin, TX","Chicago, IL",10423,13232,AUS,...,218.99,WN,0.9822,218.30,WN,0.9822,218.30,"Austin, TX\r\n(30.264979, -97.746598)","Chicago, IL\r\n(41.775002, -87.696388)",201821042313232AUSMDW
84308,Table 1a,2018,2,30423,30721,"Austin, TX","Boston, MA (Metropolitan Area)",10423,13296,AUS,...,271.86,WN,0.5267,242.69,WN,0.5267,242.69,"Austin, TX\r\n(30.264979, -97.746598)","Boston, MA (Metropolitan Area)\r\n(42.358894, ...",201821042313296AUSMHT
84309,Table 1a,2018,2,30423,32467,"Austin, TX","Miami, FL (Metropolitan Area)",10423,13303,AUS,...,229.80,AA,0.8710,233.36,UA,0.0887,174.11,"Austin, TX\r\n(30.264979, -97.746598)","Miami, FL (Metropolitan Area)\r\n(44.977479, -...",201821042313303AUSMIA
84310,Table 1a,2018,2,30423,32457,"Austin, TX","San Francisco, CA (Metropolitan Area)",10423,13796,AUS,...,220.83,WN,0.9080,219.64,WN,0.9080,219.64,"Austin, TX\r\n(30.264979, -97.746598)","San Francisco, CA (Metropolitan Area)\r\n(37.7...",201821042313796AUSOAK
84311,Table 1a,2018,2,30423,32575,"Austin, TX","Los Angeles, CA (Metropolitan Area)",10423,13891,AUS,...,170.80,WN,0.4155,196.47,F9,0.3008,86.37,"Austin, TX\r\n(30.264979, -97.746598)","Los Angeles, CA (Metropolitan Area)\r\n(34.052...",201821042313891AUSONT
84312,Table 1a,2018,2,30423,30977,"Austin, TX","Chicago, IL",10423,13930,AUS,...,223.43,AA,0.5239,224.35,UA,0.4600,220.88,"Austin, TX\r\n(30.264979, -97.746598)","Chicago, IL\r\n(41.775002, -87.696388)",201821042313930AUSORD
84313,Table 1a,2018,2,30423,30466,"Austin, TX","Phoenix, AZ",10423,14107,AUS,...,184.68,WN,0.5556,188.69,WN,0.5556,188.69,"Austin, TX\r\n(30.264979, -97.746598)","Phoenix, AZ\r\n(30.406931, -87.217578)",201821042314107AUSPHX
84314,Table 1a,2018,2,30423,33195,"Austin, TX","Tampa, FL (Metropolitan Area)",10423,14112,AUS,...,73.87,G4,1.0000,73.87,G4,1.0000,73.87,"Austin, TX\r\n(30.264979, -97.746598)","Tampa, FL (Metropolitan Area)\r\n(37.8606, -78...",201821042314112AUSPIE
84315,Table 1a,2018,2,30423,30721,"Austin, TX","Boston, MA (Metropolitan Area)",10423,14307,AUS,...,240.29,AA,0.2765,275.52,F9,0.2179,84.07,"Austin, TX\r\n(30.264979, -97.746598)","Boston, MA (Metropolitan Area)\r\n(42.358894, ...",201821042314307AUSPVD
84316,Table 1a,2018,2,30423,32457,"Austin, TX","San Francisco, CA (Metropolitan Area)",10423,14771,AUS,...,223.66,UA,0.5028,249.82,WN,0.1337,188.64,"Austin, TX\r\n(30.264979, -97.746598)","San Francisco, CA (Metropolitan Area)\r\n(37.7...",201821042314771AUSSFO
84317,Table 1a,2018,2,30423,32457,"Austin, TX","San Francisco, CA (Metropolitan Area)",10423,14831,AUS,...,216.84,WN,0.6248,224.91,AS,0.1714,211.18,"Austin, TX\r\n(30.264979, -97.746598)","San Francisco, CA (Metropolitan Area)\r\n(37.7...",201821042314831AUSSJC
84318,Table 1a,2018,2,30423,32575,"Austin, TX","Los Angeles, CA (Metropolitan Area)",10423,14908,AUS,...,247.31,WN,0.4014,240.61,UA,0.1842,235.21,"Austin, TX\r\n(30.264979, -97.746598)","Los Angeles, CA (Metropolitan Area)\r\n(34.052...",201821042314908AUSSNA
84319,Table 1a,2018,2,30423,31703,"Austin, TX","New York City, NY (Metropolitan Area)",10423,15070,AUS,...,353.23,DL,0.4717,291.35,DL,0.4717,291.35,"Austin, TX\r\n(30.264979, -97.746598)","New York City, NY (Metropolitan Area)\r\n(40.1...",201821042315070AUSSWF
84320,Table 1a,2018,2,30423,33195,"Austin, TX","Tampa, FL (Metropolitan Area)",10423,15304,AUS,...,220.83,WN,0.6370,229.33,UA,0.1287,203.53,"Austin, TX\r\n(30.264979, -97.746598)","Tampa, FL (Metropolitan Area)\r\n(37.8606, -78...",201821042315304AUSTPA